# Generated by Django 3.0.6 on 2023-03-28 13:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='abonado',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='bono',
            name='tipo',
            field=models.CharField(choices=[('comprado', 'Comprado'), ('vitalicio', 'Vitalicio'), ('cortesia', 'Cortesía'), ('palco', 'Palco'), ('seguridad', 'Seguridad'), ('operativo', 'Operativo'), ('network', 'Network'), ('directiva', 'Directiva'), ('admin', 'Administración')], default='cortesia', max_length=10),
        ),
        migrations.AlterField(
            model_name='bono',
            name='ubicacion',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
    ]
