# Generated by Django 3.0.6 on 2023-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0003_auto_20230328_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='tipo',
            field=models.CharField(choices=[('abonado', 'Abonado'), ('comprado', 'Comprado'), ('vitalicio', 'Vitalicio'), ('cortesia', 'Cortesía'), ('palco', 'Palco'), ('seguridad', 'Seguridad'), ('operativo', 'Operativo'), ('network', 'Network'), ('directiva', 'Directiva'), ('admin', 'Administración'), ('tarjeton', 'Tarjetón Est')], default='cortesia', max_length=10),
        ),
    ]
