# Generated by Django 3.0.6 on 2023-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0004_auto_20230329_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bono',
            options={'ordering': ('abonado__name',)},
        ),
        migrations.AlterField(
            model_name='bono',
            name='tipo',
            field=models.CharField(choices=[('abonado', 'Abonado'), ('comprado', 'Comprado'), ('vitalicio', 'Vitalicio'), ('cortesia', 'Cortesía'), ('palco', 'Palco'), ('seguridad', 'Seguridad'), ('operativo', 'Operativo'), ('network', 'Network'), ('directiva', 'Directiva'), ('admin', 'Administración'), ('tarjeton', 'Tarjetón Est'), ('zona_comercial', 'Zona Comercial')], default='cortesia', max_length=100),
        ),
    ]
