# Generated by Django 3.0.6 on 2023-04-25 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0005_auto_20230420_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(choices=[('centenario', 'Estadio Centenario 27 de Febrero')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bono',
            options={'ordering': ('abonado__name', 'fecha_reg')},
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('total_lecturas', models.SmallIntegerField()),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonos_partido', to='bonos.Bono')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_partido', to='bonos.Partidos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
