# Generated by Django 3.0.6 on 2023-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0006_auto_20230425_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
