# Generated by Django 3.0.6 on 2023-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0007_auto_20230425_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='total_lecturas',
            field=models.SmallIntegerField(default=0),
        ),
    ]
