# Generated by Django 3.0.6 on 2023-07-24 00:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0008_auto_20230425_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bono',
            name='pago',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
    ]
